### ISSUE TITLE
Upgrading to Professional after the trail has expired fails 

### ISSUE THREAD

**Issue by lislema** [guiqui/k8Studio#99]
The software trial license expires, you pay the 200+ dollars and there is no way the software can determine the license has been upgraded. Feels like a scam and the lack of any functionality on your website makes it very irritating 

![image](https://github.com/user-attachments/assets/aff7e9b0-2fc1-40b2-ba7f-946839284a7a)

User experience 0%

**Comment by guiqui** [comment]
Hi Mark,

I want to assure you that this was not a scam but rather an issue caused by a bug in the Stripe webhook. We completely understand how upsetting it can be to make a payment and experience this kind of issue.

Please know that we are here to resolve this for you. If you'd like a refund, we are more than willing to process it promptly. Our intention is never to cause frustration, and we value your trust.

Thank you for bringing this to our attention, and we apologize for any inconvenience caused.

**Comment by lislema** [comment]
it was fixed thank you, the company was very helpful in resolving the issue

**Comment by guiqui** [comment]
Thank you!!!
